apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
  labels:
    {{- include "w7panel-longhorn.labels" . | nindent 4 }}
spec:
  chart: https://cdn.w7.cc/w7panel/charts/longhorn/longhorn-{{ .Chart.AppVersion }}.tgz
  version: v{{ .Chart.AppVersion }}
  targetNamespace: longhorn-system
  createNamespace: true
  #
  # failurePolicy: abort 只是不让它自动卸载旧 release，不代表能直接从 uninstalling 状态继续安装。你现在这个 release 已经卡在 uninstalling，后续仍然需要手动处理 Longhorn 残留资源或 Helm
  # release 状态，否则安装可能会继续失败，只是不再自动执行 helm uninstall --wait
  #
  failurePolicy: abort 
  set:
    longhornUI.replicas: 0
    csi.attacherReplicaCount: 1
    csi.provisionerReplicaCount: 1
    csi.resizerReplicaCount: 1
    csi.snapshotterReplicaCount: 1
    defaultSettings.storageReservedPercentageForDefaultDisk: "0"
    defaultSettings.createDefaultDiskLabeledNodes: "true"
    defaultSettings.replicaSoftAntiAffinity: "true"
    defaultSettings.replicaDiskSoftAntiAffinity: "false"
    defaultSettings.replicaZoneSoftAntiAffinity: "true"
    defaultSettings.taintToleration: "node.kubernetes.io/unschedulable:NoSchedule; node.kubernetes.io/storage:NoSchedule"
    global.tolerations[0].key: node.kubernetes.io/unschedulable
    global.tolerations[0].operator: Exists
    global.tolerations[0].effect: NoSchedule
    global.tolerations[1].key: node.kubernetes.io/storage
    global.tolerations[1].operator: Exists
    global.tolerations[1].effect: NoSchedule

